/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class FeatureListFrame extends javax.swing.JFrame {

    SinhVienFrame sinhVienFrame;
    PhieuThuFrame phieuThuFrame;
    PhieuNoFrame phieuNoFrame;
    MucHocPhiFrame mucHocPhiFrame;

    public FeatureListFrame() {
        initComponents();
        sinhVienFrame = new SinhVienFrame();
        phieuThuFrame = new PhieuThuFrame();
        phieuNoFrame = new PhieuNoFrame();
        mucHocPhiFrame = new MucHocPhiFrame();
        sinhVienFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        phieuThuFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        phieuNoFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mucHocPhiFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        openSinhVienFrame = new javax.swing.JButton();
        openPhieuThuFrame = new javax.swing.JButton();
        openPhieuNoFrame = new javax.swing.JButton();
        openMucHocPhiFrame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Thongtin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH TÍNH NĂNG");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        openSinhVienFrame.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        openSinhVienFrame.setForeground(new java.awt.Color(0, 0, 153));
        openSinhVienFrame.setIcon(new javax.swing.ImageIcon("C:\\Users\\iphon\\OneDrive\\Desktop\\QLSV_new\\QLSV_new\\qlsv   v.PNG")); // NOI18N
        openSinhVienFrame.setText("Quản lí sinh viên");
        openSinhVienFrame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openSinhVienFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSinhVienFrameActionPerformed(evt);
            }
        });

        openPhieuThuFrame.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        openPhieuThuFrame.setForeground(new java.awt.Color(0, 0, 153));
        openPhieuThuFrame.setIcon(new javax.swing.ImageIcon("C:\\Users\\iphon\\OneDrive\\Desktop\\QLSV_new\\QLSV_new\\monny.png")); // NOI18N
        openPhieuThuFrame.setText("Quản lí thu học phí");
        openPhieuThuFrame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openPhieuThuFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPhieuThuFrameActionPerformed(evt);
            }
        });

        openPhieuNoFrame.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        openPhieuNoFrame.setForeground(new java.awt.Color(0, 0, 153));
        openPhieuNoFrame.setIcon(new javax.swing.ImageIcon("C:\\Users\\iphon\\OneDrive\\Desktop\\QLSV_new\\QLSV_new\\monny.png")); // NOI18N
        openPhieuNoFrame.setText("Quản lí nợ học phí");
        openPhieuNoFrame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openPhieuNoFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPhieuNoFrameActionPerformed(evt);
            }
        });

        openMucHocPhiFrame.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        openMucHocPhiFrame.setForeground(new java.awt.Color(0, 0, 153));
        openMucHocPhiFrame.setIcon(new javax.swing.ImageIcon("C:\\Users\\iphon\\OneDrive\\Desktop\\QLSV_new\\QLSV_new\\mức hp.png")); // NOI18N
        openMucHocPhiFrame.setText("Quản lí mức học phí");
        openMucHocPhiFrame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openMucHocPhiFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMucHocPhiFrameActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\iphon\\OneDrive\\Desktop\\QLSV_new\\QLSV_new\\kisspng-computer-icons-symbol-clip-art-free-exit-icon-png-5ab071c40df213.0134616015215129000571.png")); // NOI18N
        jButton1.setText("Thoát ứng dụng");
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Thongtin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Thongtin.setForeground(new java.awt.Color(0, 0, 153));
        Thongtin.setIcon(new javax.swing.ImageIcon("C:\\Users\\iphon\\OneDrive\\Desktop\\QLSV_new\\QLSV_new\\thongtin.png")); // NOI18N
        Thongtin.setText("Thông tin ứng dụng");
        Thongtin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Thongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongtinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openMucHocPhiFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openPhieuNoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openPhieuThuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openSinhVienFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(openSinhVienFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(openPhieuThuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(openPhieuNoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(openMucHocPhiFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Thongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openSinhVienFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSinhVienFrameActionPerformed
        sinhVienFrame.setVisible(true);
    }//GEN-LAST:event_openSinhVienFrameActionPerformed

    private void openPhieuThuFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPhieuThuFrameActionPerformed
        phieuThuFrame.setVisible(true);
    }//GEN-LAST:event_openPhieuThuFrameActionPerformed

    private void openPhieuNoFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPhieuNoFrameActionPerformed
        phieuNoFrame.setVisible(true);
    }//GEN-LAST:event_openPhieuNoFrameActionPerformed

    private void openMucHocPhiFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMucHocPhiFrameActionPerformed
        mucHocPhiFrame.setVisible(true);
    }//GEN-LAST:event_openMucHocPhiFrameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ThongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongtinActionPerformed
JOptionPane.showMessageDialog(this, "Thực hiện bởi : Nguyễn Thu Hương  & Trần Văn Hòa & Đào Thị Huyên ");       

    }//GEN-LAST:event_ThongtinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeatureListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeatureListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeatureListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeatureListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeatureListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Thongtin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton openMucHocPhiFrame;
    private javax.swing.JButton openPhieuNoFrame;
    private javax.swing.JButton openPhieuThuFrame;
    private javax.swing.JButton openSinhVienFrame;
    // End of variables declaration//GEN-END:variables

}
