/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.PhieuNoController;
import controller.SinhVienController;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuNo;
import model.SinhVien;
import utils.ExcelExporter;

public class PhieuNoFrame extends javax.swing.JFrame {

    DefaultTableModel phieuNoModel;

    SinhVienController sinhVienController;

    PhieuNoController phieuNoController;

    int selectedPhieuNoID = -1;

    /**
     * Creates new form PhieuNoFrame
     */
    public PhieuNoFrame() {
        initComponents();
        phieuNoModel = (DefaultTableModel) PhieuNoTbl.getModel();
        sinhVienController = new SinhVienController();
        phieuNoController = new PhieuNoController();
        showDanhSachPhieuNo();
  this.setLocationRelativeTo(null);
    }

    // Hiển thị danh sách phiếu nợ ra bảng
    private void showDanhSachPhieuNo() {
        List<PhieuNo> listPhieuNo = phieuNoController.getList();
        phieuNoModel.setRowCount(0);
        listPhieuNo.forEach((phieuNo) -> {
            phieuNoModel.addRow(new Object[]{
                phieuNo.getId(),
                phieuNo.getMaSV(),
                phieuNo.getSoTienConNo(),
                phieuNo.getNgayDaoHan(),});
        });
    }

    // Lấy thông tin phiếu nợ từ các trường nhập
    private PhieuNo getPhieuNoDataFromFields() {
        String maSV = noTienMaSVField.getText();
        String ngayDaoHan = noTienNgayDaoHanField.getText();
        String soTienNoStr = noTienSoTienNoField.getText();
        if (!maSV.isEmpty() && !ngayDaoHan.isEmpty() && !soTienNoStr.isEmpty()) {
            int soTienNo = Integer.parseInt(soTienNoStr);
            PhieuNo phieuNo = new PhieuNo(maSV, soTienNo, ngayDaoHan);
            return phieuNo;
        }
        return null;
    }

    // Điền thông tin phiếu nợ vào các ô nhập (đối với edit)
    private void fillPhieuNoFields(PhieuNo phieuNo) {
        noTienMaSVField.setText(phieuNo.getMaSV());
        noTienNgayDaoHanField.setText(phieuNo.getNgayDaoHan());
        noTienSoTienNoField.setText(phieuNo.getSoTienConNo() + "");
    }

    /**
     * Kiểm tra thông tin phiếu nợ ở đây chúng ta cũng chỉ kiểm tra xem có tồn
     * tại sinh viên không.
     */
    private boolean validatePhieuNo(PhieuNo phieuNo) {
        SinhVien sv = sinhVienController.findByMaSV(phieuNo.getMaSV());
        if (sv == null) {
            JOptionPane.showMessageDialog(this, "Không tồn tại sinh viên này. Xin hãy kiểm tra lại.");
            return false;
        }
        return true;
    }

    // Xóa thông tin ở các trường nhập phiếu nợ
    private void clearPhieuNoFields() {
        noTienMaSVField.setText("");
        noTienNgayDaoHanField.setText("");
        noTienSoTienNoField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        noTienMaSVField = new javax.swing.JTextField();
        noTienSoTienNoField = new javax.swing.JTextField();
        noTienNgayDaoHanField = new javax.swing.JTextField();
        addPhieuNoBtn = new javax.swing.JButton();
        editPhieuNoBtn = new javax.swing.JButton();
        deletePhieuNoBtn = new javax.swing.JButton();
        resetPhieuNoBtn = new javax.swing.JButton();
        exportExcelPhieuNoBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        PhieuNoTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Quản lí nợ học phí");

        jLabel14.setText("Mã sinh viên");

        jLabel15.setText("Số tiền còn nợ");

        jLabel16.setText("Ngày đáo hạn");

        addPhieuNoBtn.setText("Thêm");
        addPhieuNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhieuNoBtnActionPerformed(evt);
            }
        });

        editPhieuNoBtn.setText("Sửa");
        editPhieuNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPhieuNoBtnActionPerformed(evt);
            }
        });

        deletePhieuNoBtn.setText("Xóa");
        deletePhieuNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePhieuNoBtnActionPerformed(evt);
            }
        });

        resetPhieuNoBtn.setText("Reset");
        resetPhieuNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPhieuNoBtnActionPerformed(evt);
            }
        });

        exportExcelPhieuNoBtn.setText("Export Excel");
        exportExcelPhieuNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelPhieuNoBtnActionPerformed(evt);
            }
        });

        PhieuNoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Mã sinh viên", "Số tiền còn nợ", "Ngày đáo hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(PhieuNoTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(59, 59, 59)
                        .addComponent(noTienSoTienNoField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addPhieuNoBtn)
                            .addComponent(jLabel16))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noTienNgayDaoHanField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editPhieuNoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deletePhieuNoBtn)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(noTienMaSVField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addGap(25, 25, 25)
                .addComponent(resetPhieuNoBtn)
                .addGap(49, 49, 49)
                .addComponent(exportExcelPhieuNoBtn)
                .addGap(155, 155, 155))
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(noTienMaSVField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(noTienSoTienNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(noTienNgayDaoHanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPhieuNoBtn)
                    .addComponent(editPhieuNoBtn)
                    .addComponent(deletePhieuNoBtn)
                    .addComponent(resetPhieuNoBtn)
                    .addComponent(exportExcelPhieuNoBtn))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPhieuNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhieuNoBtnActionPerformed
        PhieuNo phieuNo = getPhieuNoDataFromFields();
        if (phieuNo != null) {
            if (validatePhieuNo(phieuNo)) {
                phieuNoController.insert(phieuNo);
                showDanhSachPhieuNo();
                clearPhieuNoFields();
                JOptionPane.showMessageDialog(this, "Thêm phieu no thanh cong. ");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xin hãy điền đầy đủ thông phiếu nợ.");
        }
    }//GEN-LAST:event_addPhieuNoBtnActionPerformed

    private void editPhieuNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPhieuNoBtnActionPerformed
        if (selectedPhieuNoID == -1) {
            int selectedIndex = PhieuNoTbl.getSelectedRow();
            if (selectedIndex >= 0) {
                int phieuNoID = Integer.parseInt(PhieuNoTbl.getValueAt(selectedIndex, 0).toString());
                PhieuNo selectedPhieuNo = phieuNoController.getOne(phieuNoID);
                selectedPhieuNoID = phieuNoID;
                fillPhieuNoFields(selectedPhieuNo);
            } else {
                JOptionPane.showMessageDialog(this, "Xin hãy chọn hàng của phiếu nợ muốn sửa.");
            }
        } else {
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn lưu lại thay đổi không? ");
            if (option == 0) {
                PhieuNo editedPhieuNo = getPhieuNoDataFromFields();
                if (editedPhieuNo != null) {
                    if (validatePhieuNo(editedPhieuNo)) {
                        phieuNoController.update(selectedPhieuNoID, editedPhieuNo);
                        selectedPhieuNoID = -1;
                        clearPhieuNoFields();
                        showDanhSachPhieuNo();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Xin hãy điền đầy đủ thông tin của phiếu nợ.");
                }
            }
        }
    }//GEN-LAST:event_editPhieuNoBtnActionPerformed

    private void deletePhieuNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePhieuNoBtnActionPerformed
        if (selectedPhieuNoID == -1) {
            int selectedIndex = PhieuNoTbl.getSelectedRow();
            if (selectedIndex >= 0) {
                int phieuNoID = Integer.parseInt(PhieuNoTbl.getValueAt(selectedIndex, 0).toString());
                selectedPhieuNoID = phieuNoID;
            } else {
                JOptionPane.showMessageDialog(this, "Xin hãy chọn hàng của phiếu nợ muốn sửa.");
            }
        } else {
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không ? ");
            if (option == 0) {
                phieuNoController.delete(selectedPhieuNoID);
                selectedPhieuNoID = -1;
                showDanhSachPhieuNo();
                JOptionPane.showMessageDialog(this, "Xóa thành công.");
            }
        }
    }//GEN-LAST:event_deletePhieuNoBtnActionPerformed

    private void resetPhieuNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPhieuNoBtnActionPerformed
        clearPhieuNoFields();
    }//GEN-LAST:event_resetPhieuNoBtnActionPerformed

    private void exportExcelPhieuNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelPhieuNoBtnActionPerformed
        try {
            ExcelExporter.exportToExcels(PhieuNoTbl);
        } catch (IOException ex) {
            Logger.getLogger(PhieuNoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exportExcelPhieuNoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuNoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PhieuNoTbl;
    private javax.swing.JButton addPhieuNoBtn;
    private javax.swing.JButton deletePhieuNoBtn;
    private javax.swing.JButton editPhieuNoBtn;
    private javax.swing.JButton exportExcelPhieuNoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField noTienMaSVField;
    private javax.swing.JTextField noTienNgayDaoHanField;
    private javax.swing.JTextField noTienSoTienNoField;
    private javax.swing.JButton resetPhieuNoBtn;
    // End of variables declaration//GEN-END:variables
}
